 <h1> Effectuez votre Réservation </h1>

 <form action="" method="post">

    <div class="form-group">
        <label for="">Date de début</label>
        <input type="date" name="debut" class="form-control" />
    </div>
    
    <div class="form-group">
        <label for="">Date de fin</label>
        <input type="date" name="fin" class="form-control" />
    </div>

    <div class="form-group">
        <label for="">Total</label>
        <input type="text" name="total" class="form-control" />
    </div>

    <label for="">client</label>
    <input type="text" name="client" value="<?=$reservation->getClient() ?>" class="form-control" />

    <label for="">vehicule</label>
    <input type="text" name="vehicule" value="<?=$reservation->getVehicule() ?>" class="form-control" />

    <button type="submit" class="btn btn-primary">Submit</button>

 </form>