 <h1> Effectuez votre Réservation </h1>

 <form action="" method="post">

    <div class="form-group">
        <label for="">Date de début</label>
        <input type="date" name="debut" class="form-control" />
    </div>
    
    <div class="form-group">
        <label for="">Date de fin</label>
        <input type="date" name="fin" class="form-control" />
    </div>

    <input type="hidden" name="client" value="<?=unserialize($_SESSION['user'])->getId() ?>" class="form-control" />
 
    <!-- <label for="">vehicule</label> -->
    <input type="hidden" name="vehicule" value="<?=$_GET['id'] ?>" class="form-control" />
 
    <input type="hidden" name="prix" value="<?=$_GET['prix_journalier'] ?>" class="form-control" />

    <button type="submit" class="btn btn-primary mt-2">Submit</button>

 </form>