
    <h2 class="text-center">Liste de Clients</h2>

    <h3>
        liste de balise h1 : &lt;h1&gt;&lt;/h1&gt;
    </h3>

    <a href="?actionUser=new" class="btn btn-success my-2">Ajouter</a>

    <?php if( !empty($users) ): ?>

    <table class="table table-striped">
        <tr class="table-dark">
            <th>Prénom</th>
            <th>Login</th>
            <th>Rôle</th>
            <th>Ville</th>
            <th>Action</th>
        </tr>

        <?php foreach($users as $user): ?>
            <tr>
                <td> <?= $user->getPrenom() ?> </td>
                <td> <?= $user->getLogin() ?> </td>
                <td> <?= $user->getRole() ?> </td>
                <td> <?= $user->getVille() ?> </td>
                <td>
                    <a href="?actionUser=update&id=<?= $user->getId() ?>"><i class="fa-solid fa-pen"></i></a> | 
                    <a href="?actionUser=delete&id=<?= $user->getId() ?>"><i class="fa-solid fa-trash"></i></a> | 
                    <a href="?actionUser=show&id=<?= $user->getId() ?>"><i class="fa-solid fa-eye"></i></a> 
                </td>
            </tr>
        <?php endforeach; ?>

    </table>

    <?php else: ?>
        <h3 class="text-center">Pas de clients en BD</h3>
    <?php endif; ?>
