
    <h2 class="text-center">new User</h2>

    <form method="post">
        
        <div class="form-group">
            <label for="exampleInputEmail1">Login</label>
            <input type="text" name="login" value="ilci1" class="form-control">
        </div>

        
        <div class="form-group">
            <label for="exampleInputEmail1">Password</label>
            <input type="password" name="mdp" value="1234" class="form-control">
        </div>

        <button type="submit" class="btn btn-primary mt-2">Submit</button>
    </form>