
    <h2 class="text-center">new User</h2>

    <form method="post">
        <div class="form-group">
            <label for="exampleInputEmail1">Prénom</label>
            <input type="text" name="prenom" required class="form-control" value="<?= $user->getPrenom() ?>">
        </div>

        
        <div class="form-group">
            <label for="exampleInputEmail1">Login</label>
            <input type="text" name="login" class="form-control" value="<?= $user->getLogin() ?>">
        </div>

        
        <div class="form-group">
            <label for="exampleInputEmail1">Password</label>
            <input type="password" name="mdp" class="form-control">
        </div>

        
        <div class="form-group">
            <label for="exampleInputEmail1">Adresse</label>
            <input type="text" name="adresse" class="form-control" value="<?= $user->getAdresse() ?>">
        </div>
        
        <div class="form-group">
            <label for="exampleInputEmail1">Code postal</label>
            <input type="number" name="cp" class="form-control" value="<?= $user->getCp() ?>">
        </div>
        
        <div class="form-group">
            <label for="exampleInputEmail1">Ville</label>
            <input type="text" name="ville" class="form-control" value="<?= $user->getVille() ?>">
        </div>


        <button type="submit" class="btn btn-primary mt-2">Submit</button>
    </form>